/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotel;

import java.awt.Color;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import Dao.HuespedDao;
import Dao.ReservaDao;
import Model.Huesped;
import Model.Reserva;

/**
 *
 * @author user
 */
public class Busqueda extends javax.swing.JFrame {
    
    private int xMouse, yMouse;

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnBUSCAR = new javax.swing.JPanel();
        BTNBUSCAR = new javax.swing.JLabel();
        BtnELIMINAR = new javax.swing.JPanel();
        BTNELIMINAR = new javax.swing.JLabel();
        BtnEDITAR = new javax.swing.JPanel();
        BTNEDITAR = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHuespedes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaReservacion = new javax.swing.JTable();
        BarraArriba = new javax.swing.JPanel();
        X = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ha-100px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 156, 233));
        jLabel2.setText("SISTEMA DE BÚSQUEDA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        BtnBUSCAR.setBackground(new java.awt.Color(0, 156, 233));

        BTNBUSCAR.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNBUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNBUSCAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNBUSCARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNBUSCARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNBUSCARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnBUSCARLayout = new javax.swing.GroupLayout(BtnBUSCAR);
        BtnBUSCAR.setLayout(BtnBUSCARLayout);
        BtnBUSCARLayout.setHorizontalGroup(
            BtnBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNBUSCAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BtnBUSCARLayout.setVerticalGroup(
            BtnBUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNBUSCAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(BtnBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 120, 40));

        BtnELIMINAR.setBackground(new java.awt.Color(0, 156, 233));

        BTNELIMINAR.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTNELIMINAR.setText("ELIMINAR");
        BTNELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNELIMINARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNELIMINARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNELIMINARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnELIMINARLayout = new javax.swing.GroupLayout(BtnELIMINAR);
        BtnELIMINAR.setLayout(BtnELIMINARLayout);
        BtnELIMINARLayout.setHorizontalGroup(
            BtnELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNELIMINAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BtnELIMINARLayout.setVerticalGroup(
            BtnELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNELIMINAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(BtnELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 120, 40));

        BtnEDITAR.setBackground(new java.awt.Color(0, 156, 233));

        BTNEDITAR.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNEDITAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNEDITAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNEDITAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNEDITARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNEDITARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNEDITARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnEDITARLayout = new javax.swing.GroupLayout(BtnEDITAR);
        BtnEDITAR.setLayout(BtnEDITARLayout);
        BtnEDITARLayout.setHorizontalGroup(
            BtnEDITARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNEDITAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BtnEDITARLayout.setVerticalGroup(
            BtnEDITARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNEDITAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(BtnEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 120, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 156, 233));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 200, 10));
        jSeparator1.getAccessibleContext().setAccessibleName("");
        jSeparator1.getAccessibleContext().setAccessibleDescription("");

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 200, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 233), 2));

        TablaHuespedes.setFont(new java.awt.Font("RobotoMono Nerd Font Mono", 0, 18)); // NOI18N
        MostrarTablaHuespedes();
        jScrollPane1.setViewportView(TablaHuespedes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HUÉSPEDES", new javax.swing.ImageIcon(getClass().getResource("/imagenes/persona.png")), jPanel2); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 233), 2));

        TablaReservacion.setFont(new java.awt.Font("RobotoMono Nerd Font Mono", 0, 18)); // NOI18N
        MostrarTablaReserva();
        jScrollPane2.setViewportView(TablaReservacion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RESERVA", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 840, 350));

        BarraArriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraArribaMouseDragged(evt);
            }
        });
        BarraArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraArribaMousePressed(evt);
            }
        });

        X.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        X.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 40, 30));

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraArribaLayout.createSequentialGroup()
                .addGap(0, 900, Short.MAX_VALUE)
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraArribaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNBUSCARMouseClicked
        String apellido = jTextField1.getText();
        try {
            Long.parseLong(apellido);
            MostrarTablaHuespedesBuscados(apellido);
        } catch (Exception e) {
          MostrarTablaHuespedesBuscados(apellido);
        }finally {
            jScrollPane1.setViewportView(TablaHuespedes);
        }
        
    }

    private void BTNBUSCARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNBUSCARMouseEntered
        BtnBUSCAR.setBackground(new Color(0,170,240));
    }//GEN-LAST:event_BTNBUSCARMouseEntered

    private void BTNBUSCARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNBUSCARMouseExited
        BtnBUSCAR.setBackground(new Color(0,156,233));
    }//GEN-LAST:event_BTNBUSCARMouseExited

    private void BTNELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNELIMINARMouseClicked
        // CLICK PARA ELIMINAR ALGO EN LA TABLA
    }//GEN-LAST:event_BTNELIMINARMouseClicked

    private void BTNELIMINARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNELIMINARMouseEntered
        BtnELIMINAR.setBackground(new Color(0,170,240));
    }//GEN-LAST:event_BTNELIMINARMouseEntered

    private void BTNELIMINARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNELIMINARMouseExited
         BtnELIMINAR.setBackground(new Color(0,156,233));
    }//GEN-LAST:event_BTNELIMINARMouseExited

    private void BTNEDITARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNEDITARMouseClicked
        // cLICK AL BOTON EDITAR PROGRAMAR ACCION
    }//GEN-LAST:event_BTNEDITARMouseClicked

    private void BTNEDITARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNEDITARMouseEntered
        BtnEDITAR.setBackground(new Color(0,170,240));
    }//GEN-LAST:event_BTNEDITARMouseEntered

    private void BTNEDITARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNEDITARMouseExited
        BtnEDITAR.setBackground(new Color(0,156,233));
    }//GEN-LAST:event_BTNEDITARMouseExited

    private void BarraArribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraArribaMouseDragged
    int x = evt.getX();
    int y = evt.getY();
    this.setLocation(this.getX() + x - xMouse, this.getY() + y - yMouse);
    repaint();
    }//GEN-LAST:event_BarraArribaMouseDragged

    private void BarraArribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraArribaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); 
    }//GEN-LAST:event_BarraArribaMousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    void MostrarTablaHuespedes(){

        HuespedDao buscar = new HuespedDao();
        List<Huesped> Listatabla = buscar.Consultar();
        
        DefaultTableModel model = new DefaultTableModel();

        // Agrega las columnas al modelo de la tabla
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Fecha_nacimiento");
        model.addColumn("Nacionalidad");
        model.addColumn("Telefono");
        model.addColumn("Reserva");

        // Llena las filas del modelo con los datos de los productos
        for (Huesped huesped : Listatabla) {
            model.addRow(new Object[] {
                    huesped.getId(),
                    huesped.getNombre(),
                    huesped.getApellido(),
                    huesped.getFecha_nacimiento(),
                    huesped.getNacionalidad(),
                    huesped.getTelefono(),
                    huesped.getReserva()
            });
        }

        // Establece el modelo en la tabla
        TablaHuespedes.setModel(model);
    }
    void MostrarTablaHuespedesBuscados(String apellido){

        HuespedDao buscar = new HuespedDao();
        List<Huesped> Listatabla = buscar.ConsultaApellido(apellido);
        
        DefaultTableModel model = new DefaultTableModel();

        // Agrega las columnas al modelo de la tabla
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Fecha_nacimiento");
        model.addColumn("Nacionalidad");
        model.addColumn("Telefono");
        model.addColumn("Reserva");

        // Llena las filas del modelo con los datos de los productos
        for (Huesped huesped : Listatabla) {
            model.addRow(new Object[] {
                    huesped.getId(),
                    huesped.getNombre(),
                    huesped.getApellido(),
                    huesped.getFecha_nacimiento(),
                    huesped.getNacionalidad(),
                    huesped.getTelefono(),
                    huesped.getReserva()
            });
        }

        // Establece el modelo en la tabla
        TablaHuespedes.setModel(model);
    }

    void MostrarTablaReserva(){

        ReservaDao buscar = new ReservaDao();
        List<Reserva> Listatabla = buscar.Consultar();
        
        DefaultTableModel model = new DefaultTableModel();

        // Agrega las columnas al modelo de la tabla
        model.addColumn("ID");
        model.addColumn("Fecha Entrada");
        model.addColumn("Fecha Salida");
        model.addColumn("Valor Reserva");
        model.addColumn("Forma de Pago");

        // Llena las filas del modelo con los datos de los productos
        for (Reserva Reserva : Listatabla) {
            model.addRow(new Object[] {

                Reserva.getReserca_id(),
                Reserva.getChechin(),
                Reserva.getCheckout(),
                Reserva.getValor_reserva(),
                Reserva.getForma_pago()



            });
        }

        // Establece el modelo en la tabla
        TablaReservacion.setModel(model);
    }

    void MostrarTablaReserva(Long Id){

        ReservaDao buscar = new ReservaDao();
        List<Huesped> Listatabla = buscar.ConsultarReservaId(Id);
        
        DefaultTableModel model = new DefaultTableModel();

        // Agrega las columnas al modelo de la tabla
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Fecha_nacimiento");
        model.addColumn("Nacionalidad");
        model.addColumn("Telefono");
        model.addColumn("Reserva");

        // Llena las filas del modelo con los datos de los productos
        for (Huesped huesped : Listatabla) {
            model.addRow(new Object[] {
                    huesped.getId(),
                    huesped.getNombre(),
                    huesped.getApellido(),
                    huesped.getFecha_nacimiento(),
                    huesped.getNacionalidad(),
                    huesped.getTelefono(),
                    huesped.getReserva()
            });
        }
        // Establece el modelo en la tabla
        TablaHuespedes.setModel(model);
    }

    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTNBUSCAR;
    private javax.swing.JLabel BTNEDITAR;
    private javax.swing.JLabel BTNELIMINAR;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JPanel BtnBUSCAR;
    private javax.swing.JPanel BtnEDITAR;
    private javax.swing.JPanel BtnELIMINAR;
    private javax.swing.JTable TablaHuespedes;
    private javax.swing.JTable TablaReservacion;
    private javax.swing.JPanel X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
