/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotel;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

import Dao.ReservaDao;
import Model.FormasPago;
import Model.Reserva;
import views.TextPrompt;

/**
 *
 * @author user
 */
public class SistemaReserva extends javax.swing.JFrame {

    private int xMouse, yMouse;
    public Reserva reservacion;
    public FormasPago formaPagoSeleccionada;
    private long diasDiferencia;

    /**
     * Creates new form SistemaReserva
     */
    public SistemaReserva() {
        initComponents();
        TextPrompt holder = new TextPrompt("yyyy-mm-dd", TextCheckOut);
        TextPrompt holder1 = new TextPrompt("yyyy-mm-dd", TextCheckin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        X = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BtnConti = new javax.swing.JPanel();
        BtnContinua = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextCheckOut = new javax.swing.JTextField();
        TextCheckin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        ValorReservacion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ComBoxFormaDePago = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BarraArriba = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservas-img-3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 490, 400));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ha-100px.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        X.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        X.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));




        BtnConti.setBackground(new java.awt.Color(0, 156, 233));

        BtnContinua.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        BtnContinua.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnContinua.setText("Continuar");
        BtnContinua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnContinua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContinuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnContinuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnContinuaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnContiLayout = new javax.swing.GroupLayout(BtnConti);
        BtnConti.setLayout(BtnContiLayout);
        BtnContiLayout.setHorizontalGroup(
            BtnContiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnContinua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        BtnContiLayout.setVerticalGroup(
            BtnContiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnContinua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(BtnConti, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 140, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 156, 233));
        jLabel4.setText("Sistema De Reserva.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel5.setText("FECHA CHECK OUT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel9.setText("FECHA CHECK IN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        TextCheckOut.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        TextCheckOut.setBorder(null);
        TextCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });
        getContentPane().add(TextCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 310, 40));

        TextCheckin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        TextCheckin.setBorder(null);
        getContentPane().add(TextCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 310, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 156, 233));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 310, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 156, 233));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 10));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel10.setText("VALOR DE LA RESERVA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        ValorReservacion.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        ValorReservacion.setText("$"+(diasDiferencia * 50));
        getContentPane().add(ValorReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel12.setText("FORMA DE PAGO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 156, 233));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, 10));

        ComBoxFormaDePago.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        ComBoxFormaDePago.setModel(new javax.swing.DefaultComboBoxModel<>(FormasPago.values()));
                    // Agregar ActionListener al JComboBox para capturar la selección del usuario
            ComBoxFormaDePago.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    formaPagoSeleccionada = (FormasPago) ComBoxFormaDePago.getSelectedItem();
                }
            });
        getContentPane().add(ComBoxFormaDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Panel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        BarraArriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraArribaMouseDragged(evt);
            }
        });
        BarraArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraArribaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked



    private void BtnContinuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuaMouseEntered
        BtnConti.setBackground(new Color(0, 170, 240));
    }//GEN-LAST:event_BtnContinuaMouseEntered

    private void BtnContinuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuaMouseExited
        BtnConti.setBackground(new Color(0, 156, 233));
    }//GEN-LAST:event_BtnContinuaMouseExited

    private void BtnContinuaMouseClicked(java.awt.event.MouseEvent evt) {

        String fecha1 = TextCheckin.getText();
        String fecha2 = TextCheckOut.getText();
        if(fecha2.isEmpty() || fecha1.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, 
            "Debe llenar todos los campos.");
        }else{

        LocalDate localDate = LocalDate.parse(fecha1);
        LocalDate localDate2 = LocalDate.parse(fecha2);
        diasDiferencia = ChronoUnit.DAYS.between(localDate, localDate2);
        this.reservacion = new Reserva(localDate, localDate2, new BigDecimal((diasDiferencia * 50)), formaPagoSeleccionada);
        RegistroHuesped in = new RegistroHuesped(reservacion);
        in.setVisible(true);
        this.dispose();
        }
    }
    

    private void BarraArribaMousePressed(java.awt.event.MouseEvent evt) {
        xMouse = evt.getX();
        yMouse = evt.getY();
    }

    private void BarraArribaMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getX();
        int y = evt.getY();
        this.setLocation(this.getX() + x - xMouse, this.getY() + y - yMouse);
        repaint();
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    private javax.swing.JPanel BarraArriba;
    private javax.swing.JPanel BtnConti;
    private javax.swing.JLabel BtnContinua;
    private javax.swing.JComboBox<FormasPago> ComBoxFormaDePago;
    private javax.swing.JTextField TextCheckOut;
    private javax.swing.JTextField TextCheckin;
    private javax.swing.JLabel ValorReservacion;
    private javax.swing.JPanel X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;

}
